@baseurl = http://localhost:3000/api

###
POST {{baseurl}}/products
Content-Type: application/json 

{
  "name": "admin",
  "description": ""
}

###
POST {{baseurl}}/categories
Content-Type: application/json 

{
  "name": "Electronics",
  "title": "Electronic Devices and Accessories",
  "subtitle": "Gadgets, devices, and more",
  "images": [
    "image1.jpg",
    "image2.jpg"
  ]
}

###

GET {{baseurl}}/categories
Content-Type: application/json 